=== Leo-Ace/XML_Basic/Product.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="productNameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="3"/>
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="categoryIdType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="9"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="productDescriptionType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="128"/>
      <xs:pattern value="[^!@#$%^*()_+|\]\[\}\{?&lt;&gt;&amp;]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="productAmountType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="9999"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="productPriceType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="imageType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\\s]+\.(jpg|png)"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="productType">
    <xs:sequence>
      <xs:element name="id" type="xs:integer"/>
      <xs:element name="name" type="productNameType"/>
      <xs:element name="category_id" type="categoryIdType"/>
      <xs:element name="description" type="productDescriptionType"/>
      <xs:element name="amount" type="productAmountType"/>
      <xs:element name="price" type="productPriceType"/>
      <xs:element name="size"/>
      <xs:element name="image">
        <xs:complexType >
          <xs:simpleContent>
            <xs:extension base="imageType">
              <xs:attribute name="type" type="xs:string"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="DSSanpham">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Sanpham" type="productType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:unique name="uniqueProductId">
      <xs:selector xpath="Sanpham" />
      <xs:field xpath="id" />
    </xs:unique>
  </xs:element>

</xs:schema>

=== Leo-Ace/XML_Basic/Product.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="showData.xslt" type="text/xsl"?>
<!-- <?xml-stylesheet href="sortByName.xslt" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="showAo.xslt" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="formatByPriceAndSize.xslt" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="formatByAmount.xslt" type="text/xsl"?> -->

<DSSanpham xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Product.xsd">
  <Sanpham>
    <id>1</id>
    <name>Áo sơ mi</name>
    <category_id>1</category_id>
    <description>Sơ mi cao cấp</description>
    <amount>0</amount>
    <price>1000000</price>
    <size>M</size>
    <image type="jpg">a.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>2</id>
    <name>Quần bò</name>
    <category_id>2</category_id>
    <description>Quần bò rách</description>
    <amount>200</amount>
    <price>200000</price>
    <size>L</size>
    <image type="png">Anh.png</image>
  </Sanpham>
  <Sanpham>
    <id>3</id>
    <name>Quần âu</name>
    <category_id>3</category_id>
    <description>Quần Âu</description>
    <amount>1000</amount>
    <price>1000000</price>
    <size>XL</size>
    <image type="jpg">1.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>4</id>
    <name>Quần ngố</name>
    <category_id>4</category_id>
    <description>Ngố tàu</description>
    <amount>1</amount>
    <price>100000000</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>5</id>
    <name>Quần 5</name>
    <category_id>5</category_id>
    <description>Quần 5</description>
    <amount>1</amount>
    <price>100000000</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>6</id>
    <name>Áo 6</name>
    <category_id>4</category_id>
    <description>Ngố tàu</description>
    <amount>4</amount>
    <price>100000000</price>
    <size>XL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>7</id>
    <name>Áo 7</name>
    <category_id>1</category_id>
    <description>Ngố tàu</description>
    <amount>1</amount>
    <price>100</price>
    <size>X</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>8</id>
    <name>Quần 8</name>
    <category_id>4</category_id>
    <description>8 tàu</description>
    <amount>0</amount>
    <price>10000</price>
    <size>XL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>9</id>
    <name>Quần 9</name>
    <category_id>9</category_id>
    <description>9 tàu</description>
    <amount>1</amount>
    <price>100</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>10</id>
    <name>Áo 10</name>
    <category_id>4</category_id>
    <description>Ngố tàu</description>
    <amount>1</amount>
    <price>100</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>11</id>
    <name>Áo 11</name>
    <category_id>1</category_id>
    <description>Ngố tàu</description>
    <amount>111</amount>
    <price>111</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>12</id>
    <name>Quần 12</name>
    <category_id>4</category_id>
    <description>Ngố tàu</description>
    <amount>1</amount>
    <price>100</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>13</id>
    <name>Quần 13</name>
    <category_id>7</category_id>
    <description>Ngố 13</description>
    <amount>0</amount>
    <price>100</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>14</id>
    <name>Quần 14</name>
    <category_id>4</category_id>
    <description>Ngố tàu</description>
    <amount>1</amount>
    <price>100</price>
    <size>XL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>15</id>
    <name>Quần 15</name>
    <category_id>4</category_id>
    <description>Ngố tàu</description>
    <amount>1</amount>
    <price>1022</price>
    <size>L</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>16</id>
    <name>Áo 16</name>
    <category_id>4</category_id>
    <description>Ngố 16</description>
    <amount>0</amount>
    <price>1002</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>17</id>
    <name>Quần 17</name>
    <category_id>4</category_id>
    <description>Ngố tàu</description>
    <amount>1</amount>
    <price>1000</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>18</id>
    <name>Quần 18</name>
    <category_id>4</category_id>
    <description>Ngố tàu</description>
    <amount>1</amount>
    <price>1000</price>
    <size>X</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>19</id>
    <name>Áo ngố</name>
    <category_id>4</category_id>
    <description>Ngố 19</description>
    <amount>1</amount>
    <price>1033</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
  <Sanpham>
    <id>20</id>
    <name>Quần 20</name>
    <category_id>4</category_id>
    <description>Ngố 20</description>
    <amount>1</amount>
    <price>10000</price>
    <size>XXL</size>
    <image type="jpg">Pro.jpg</image>
  </Sanpham>
</DSSanpham>
